### ISSUE TITLE
Support binaries not at the top level for adding to PATH

### ISSUE THREAD

**Issue by kasuboski** [jaxxstorm/action-install-gh-release#25]
If a github release has the binary under a bin folder it won't be easily accessible. It won't be found using the existing PATH add of just the top level folder.

It would be nice if the action included an option to specify an additional folder to add or perhaps add an output for the full path to the extracted folder.

**Comment by ievgenii-shepeliuk** [comment]
Hello @jaxxstorm 

What is about the issue ?

For example, this project has nested folder inside the release archive.
https://github.com/grafana/k6/releases

**Comment by jaxxstorm** [comment]
I don't currently have plans to implement this, but will leave it open in the event someone else wants to or finds time
