### ISSUE TITLE
Node12 is deprecated, upgrade to Node16

### ISSUE THREAD

**Issue by jrobison-sb** [jaxxstorm/action-install-gh-release#31]
I'm using this action by way of `uses: jaxxstorm/action-install-gh-release@v1.7.1`, and in the workflow UI I see this deprecation notice:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: jaxxstorm/action-install-gh-release

As per the doc linked in the recommendation, this action should be upgraded to Node16.

**Comment by edgeb1-roche** [comment]
Concur, I'm seeing the same thing.
