### ISSUE TITLE
Error when 'tag' key is removed

### ISSUE THREAD

**Issue by winstxnhdw** [jaxxstorm/action-install-gh-release#40]
![image](https://user-images.githubusercontent.com/56998716/218315546-00a59b4b-af06-444d-b3ba-c8a34bb0a24b.png)

Looking into the source, this seems to be an easy fix. Not sure if this was meant to be intentional though. I can push a PR if you are okay with it.

```ts
const tag = core.getInput("tag");
if (!tag) {
    throw new Error(
        `Tag not specified`
    )
}
```

**Comment by jaxxstorm** [comment]
Would happily accept a PR, if the tag isn't specified we should really look for the latest release

**Comment by winstxnhdw** [comment]
Hey @jaxxstorm,

Please review the PR.
