### ISSUE TITLE
Remove warning for pure binary releases

### ISSUE THREAD

**Issue by mteodori** [jaxxstorm/action-install-gh-release#41]
When using the action for the documented pure binary releases scenario a warning shows in the execution summary which is not needed as that is the desired behaviour, would it make sense to remove it? thanks

https://github.com/jaxxstorm/action-install-gh-release/blob/f2bcf7617d36fea65f0a9d261d4947b19947956e/src/main.ts#L218-L219

**Comment by jaxxstorm** [comment]
This could probably be an info log message rather than a warning
