### ISSUE TITLE
Publish a release with `binaries-location`

### ISSUE THREAD

**Issue by DavidGregory084** [jaxxstorm/action-install-gh-release#49]
Hey @jaxxstorm, thanks for this really useful action!

Is there any chance that you could publish a release with the changes from #44 when you have time?

I'm trying to use this to install [Binaryen](https://github.com/WebAssembly/binaryen), which uses a `bin/` folder to store binaries.

**Comment by jaxxstorm** [comment]
Should be available as v1.10.0

**Comment by DavidGregory084** [comment]
That's awesome, thanks!
