### ISSUE TITLE
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20:

### ISSUE THREAD

**Issue by bramp** [jaxxstorm/action-install-gh-release#78]
When using this action I get the following warning:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: jaxxstorm/action-install-gh-release@HEAD. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

This seems like a simple fix, but I'm unsure how to test the action.

**Comment by jaxxstorm** [comment]
This is resolved in v1.11.0
